<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-02-08T22:54:43 GMT-08:00" name="Default suite" finished-at="2023-02-08T22:55:37 GMT-08:00" duration-ms="53752">
    <groups>
    </groups>
    <test started-at="2023-02-08T22:54:43 GMT-08:00" name="Default test" finished-at="2023-02-08T22:55:37 GMT-08:00" duration-ms="53752">
      <class name="org.example.eCommerce_tc_2">
        <test-method is-config="true" signature="ConfigureAppium()[pri:0, instance:org.example.eCommerce_tc_2@54e1c68b]" started-at="2023-02-08T22:54:43 GMT-08:00" name="ConfigureAppium" finished-at="2023-02-08T22:54:52 GMT-08:00" duration-ms="9661" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ConfigureAppium -->
        <test-method is-config="true" signature="preSetup()[pri:0, instance:org.example.eCommerce_tc_2@54e1c68b]" started-at="2023-02-08T22:54:52 GMT-08:00" name="preSetup" finished-at="2023-02-08T22:54:56 GMT-08:00" duration-ms="3824" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preSetup -->
        <test-method signature="FillForm_ErrorValidation()[pri:0, instance:org.example.eCommerce_tc_2@54e1c68b]" started-at="2023-02-08T22:54:56 GMT-08:00" name="FillForm_ErrorValidation" finished-at="2023-02-08T22:55:10 GMT-08:00" duration-ms="14023" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Please enter your name> but was:<Please your name>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Please enter your name> but was:<Please your name>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:125)
at org.example.eCommerce_tc_2.FillForm_ErrorValidation(eCommerce_tc_2.java:39)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FillForm_ErrorValidation -->
        <test-method is-config="true" signature="preSetup()[pri:0, instance:org.example.eCommerce_tc_2@54e1c68b]" started-at="2023-02-08T22:55:10 GMT-08:00" name="preSetup" finished-at="2023-02-08T22:55:14 GMT-08:00" duration-ms="3941" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- preSetup -->
        <test-method signature="FillForm_PositiveFlow()[pri:0, instance:org.example.eCommerce_tc_2@54e1c68b]" started-at="2023-02-08T22:55:14 GMT-08:00" name="FillForm_PositiveFlow" finished-at="2023-02-08T22:55:36 GMT-08:00" duration-ms="21478" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FillForm_PositiveFlow -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:org.example.eCommerce_tc_2@54e1c68b]" started-at="2023-02-08T22:55:36 GMT-08:00" name="tearDown" finished-at="2023-02-08T22:55:37 GMT-08:00" duration-ms="793" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- org.example.eCommerce_tc_2 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
